# Generated by Django 3.1.3 on 2020-11-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=5)),
                ('central_bank', models.CharField(max_length=100)),
                ('current_interest_rate', models.URLField()),
                ('currency_history', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='currency_pics')),
            ],
        ),
    ]
