# Generated by Django 3.1.3 on 2020-11-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_history',
            field=models.CharField(max_length=200),
        ),
    ]
