# Generated by Django 3.1.3 on 2020-12-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_auto_20201126_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['id']},
        ),
    ]
