# Generated by Django 3.1.3 on 2020-11-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_auto_20201125_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_history',
            field=models.TextField(),
        ),
    ]
